## Generating Random Numbers

Import the random module and generate a random probability. 

In [1]:
import random

In [7]:
aleatorio = random.randint(1, 100)
print(aleatorio)

10


Then, generate a random integer within the range of 1 and 20. 

In [8]:
aleatorio = random.randint(1, 20)
print(aleatorio)

12


Finally, import NumPy and create a 3 x 5-dimensional array, filled with random integers within the range of 1 and 20.

In [12]:
import numpy as np

In [13]:
dimensionalarray3x5 = np.random.randint(1, 20, (3, 5))

In [14]:
print(dimensionalarray3x5)

[[13 17 11 12  7]
 [19  9  4  3  9]
 [ 1 18  2  7 13]]


In [15]:
dimensionalarray3x5.shape

(3, 5)